blank_issues_enabled: false
contact_links:
  - name: CubeDev Discord
    url: https://discord.gg/ERVgpfg
    about: If you are having trouble with config, come and ask us in the weaponmechanicscosmetics-support channel