name: Performance Problems
description: Report issues involving performance (High resource usage)
labels: [ bug ]
body:
  - type: checkboxes
    attributes:
      label: Did you ask for help before reporting the performance issue?
      description: Before creating an issue, use the `#weaponmechanics-support` channel of our [discord](https://discord.gg/ERVgpfg)
      options:
        - label: I have asked for help
          required: true
        - label: The developers told me to make an issue here
          required: true

  - type: input
    attributes:
      label: Timings Link
      description: Paste a **link** to your timings report. To get a report, use `/timings start`, wait a few minutes, then use `/timings paste` and put that link here.
      placeholder: |
        Example: https://timings.aikar.co/?id=6b48586fbbdd48e585ca0ebb07c59dd0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        What are you doing when the lag happens? Are you shooting a gun, causing explosions, running commands?

        Do you best to be as descriptive as possible here. Performance problems can be difficult to pinpoint, so it is important we have a list of instructions on how we can repoduce the error.
        You should be including all of your weapons config (Put the `WeaponMechanics` folder into a zip file and upload it here).
        Usually, a performance problem occurs during the usage of a specific weapon. Try testing 1 weapon at a time until you find which one causes the lag.

        Tip: You can "drag and drop" files into the text box to upload images, logs, videos, or other files.
      value: |
        Paste your `WeaponMechanics` folder into a `.zip` file and upload it.

        ```yaml
        # Paste config snippets here, if applicable. Otherwise, delete this bit.
        # You can also drag and drop your config
        ```

        Include steps to repoduce, like:
        1. Spawn in my minigun using `/wm get Minigun`
        2. Spin around 4 times
        3. Open and close your inventory
        4. Shoot the minigun
        5. You'll notice lagspikes start to occur after this
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version and Log
      description: |
        Please include a screenshot of your `/wm info` command, as well as your `latest.log` file.
        You **MUST** include **BOTH** your screenshot, and the log.
      placeholder: |
        To insert files:
        1. Try dragging and dropping files
        2. Try copying and pasting files
        3. If you are having trouble uploading files, use https://paste.gg
      render: markdown
    validations:
      required: true
